---
- name: Set the correct Github API endpoint based on version
  set_fact:
    github_api_endpoint: "{{ 'https://api.github.com/repos/borgbackup/borg/releases/latest' if borgbackup_version == 'latest' else 'https://api.github.com/repos/borgbackup/borg/releases/tags/'+ borgbackup_version}}"
    
- name: Get version {{ borgbackup_version }} of a borgbackup repository
  delegate_to: localhost
  run_once: True
  uri:
    url: "{{github_api_endpoint}}"
  register: borg_latest

- name: Download borg backup
  get_url:
    dest: "/tmp/borg"
    mode: "0755"
    url: "https://github.com/borgbackup/borg/releases/download/{{ borg_latest.json.tag_name }}/borg-linux64"
    force: yes
  delegate_to: localhost

- name: Install borg backup
  copy: 
    src: "/tmp/borg"
    dest: "/usr/local/bin/borg"
    owner: "{{ borgbackup_owner }}"
    group: "{{ borgbackup_group }}"
    mode: "0755"

- name: install borg support packages
  apt: 
    name: '{{ borgbackup_packages }}'
    force_apt_get: yes
  when: ansible_os_family is defined and ansible_os_family == "Debian"

- name: install borg
  apk:
    name: 'borgbackup'
  when: ansible_distribution == "Alpine"

- name: install borg support packages
  apk:
    name: '{{ borgbackup_packages }}'
  when: ansible_distribution == "Alpine"
